services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./partidas.db:/app/partidas.db  # Persistir o banco de dados localmente
    environment:
      FLASK_RUN_HOST: 0.0.0.0  # Garantir que o Flask escute em todas as interfaces
